services:
  payfront:
    image: "node:20.17-alpine"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node
    env_file: ".env"
    working_dir: "/home/node"
    user: "node"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
  ngrok-proxy:
    image: "ngrok/ngrok:3.3.1-alpine"
    env_file: ".env"
    environment:
    network_mode: "host"
    command: http 3000